### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by nazmulidris** [r3bl-org/shorty-idea-plugin#3]
IDEA reports this error in the logs sometimes (when a project is closed right after being opened).

```
2020-04-23 17:42:28,472 [  13954]  ERROR - pplication.impl.LaterInvocator - IntelliJ IDEA 2020.1.1 Preview  Build #IC-201.7223.18 
2020-04-23 17:42:28,473 [  13955]  ERROR - pplication.impl.LaterInvocator - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-04-23 17:42:28,473 [  13955]  ERROR - pplication.impl.LaterInvocator - OS: Mac OS X 
2020-04-23 17:42:28,473 [  13955]  ERROR - pplication.impl.LaterInvocator - Plugin to blame: Shorty - URL Shortener version: 1.2 
2020-04-23 17:42:28,473 [  13955]  ERROR - pplication.impl.LaterInvocator - Last Action: EditorBackSpace 
2020-04-23 17:42:28,513 [  13995]  ERROR - pplication.impl.LaterInvocator - null 
java.lang.AssertionError
	at com.intellij.openapi.actionSystem.AnActionEvent.getRequiredData(AnActionEvent.java:213)
	at actions.ActionUtilsKt.mustHaveLinkSelected(ActionUtils.kt:46)
	at actions.EditorReplaceLink.update(EditorReplaceLink.kt:138)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:177)
	at com.intellij.ide.util.gotoByName.GotoActionModel.updateActionBeforeShow(GotoActionModel.java:314)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.lambda$getPresentation$0(GotoActionModel.java:655)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.getPresentation(GotoActionModel.java:659)
	at com.intellij.ide.util.gotoByName.GotoActionModel$GotoActionListCellRenderer.getListCellRendererComponent(GotoActionModel.java:755)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase.lambda$null$2(ChooseByNameBase.java:626)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase.lambda$initUI$3(ChooseByNameBase.java:625)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:186)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1389)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2785)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:219)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:199)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:246)
	at java.desktop/javax.swing.DefaultListSelectionModel.insertIndexInterval(DefaultListSelectionModel.java:670)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.intervalAdded(BasicListUI.java:2743)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:153)
	at com.intellij.ide.util.gotoByName.SmartPointerListModel.access$000(SmartPointerListModel.java:31)
	at com.intellij.ide.util.gotoByName.SmartPointerListModel$1.intervalAdded(SmartPointerListModel.java:38)
	at java.desktop/javax.swing.AbstractListModel.fireIntervalAdded(AbstractListModel.java:153)
	at com.intellij.ui.CollectionListModel.addAll(CollectionListModel.java:68)
	at com.intellij.ide.util.gotoByName.SmartPointerListModel.addAllToModel(SmartPointerListModel.java:82)
	at com.intellij.ide.util.gotoByName.ModelDiff$InsertCmd.apply(ModelDiff.java:123)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase.appendToModel(ChooseByNameBase.java:1028)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase.setElementsToList(ChooseByNameBase.java:973)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase.backgroundCalculationFinished(ChooseByNameBase.java:923)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase.access$2400(ChooseByNameBase.java:86)
	at com.intellij.ide.util.gotoByName.ChooseByNameBase$CalcElementsThread.lambda$performInReadAction$1(ChooseByNameBase.java:1356)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4$1.run(ProgressIndicatorUtils.java:203)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by nazmulidris** [comment]
This problem occurs because the ActionUtils.mustHaveLinkSelected(AnActionEvent) method does the wrong thing and makes a call to getRequiredData(...). This can't happen in the update() method, since this is where you have to decide whether required IDE objects are available, such that getRequiredData(...) can be called in actionPerformed(). The following code should fix this (this hasn't been tested):

```kotlin
fun mustHaveLinkSelected(e: AnActionEvent) {
  val project = e.project
  val editor = e.getData(CommonDataKeys.EDITOR)
  val psiFile = e.getData(CommonDataKeys.PSI_FILE)

  // Project is being disposed or require IDE objects are not available.
  if (project?.isDisposed == true || editor == null || psiFile == null) {
    e.presentation.isEnabledAndVisible = false
    return
  }

  // Acquire a read lock in order to find the link information.
  val linkNode = runReadAction {
    val offset = editor.caretModel.offset
    val elementAtCaret: PsiElement? = psiFile.findElementAt(offset)
    findLink(elementAtCaret, psiFile, null)
  }

  e.presentation.isEnabledAndVisible = linkNode != null
}
```
